FROM ubuntu:24.04

# Install utils to help make life easier
RUN apt update;
RUN apt install unzip wget vim xvfb net-tools dos2unix -y

# Install Wine so that we can run Windows programs under Linux
RUN dpkg --add-architecture i386; mkdir -pm755 /etc/apt/keyrings;
RUN wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key;
RUN wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources;
RUN apt update;
RUN apt install --install-recommends winehq-stable -y

# Install Steamcmd
# For info, see: https://developer.valvesoftware.com/wiki/SteamCMD
RUN add-apt-repository multiverse; apt update
RUN echo steam steam/question select "I AGREE" | debconf-set-selections; echo steam steam/license note '' | debconf-set-selections
RUN apt install steamcmd -y; ln -s /usr/games/steamcmd /usr/bin/steamcmd
